#!/bin/ksh
#
#	This is a rewrite of the script sgetfiles.ksh but renamed to dwh_sgetfiles.ksh
#
#	The purpose is to reduce network traffic generated by the
#		original script
#
#	It accepts the original syntax, but ignores all of the
#		passed parameters
#
exec 2>/tmp/$(basename $0 .ksh).trace.$(date +%Y%m%d_%H%M)
set -x

ps -ef|grep process_dwh_lists.ksh|grep -v grep|wc  -l|read COUNT
[ $COUNT -gt 0 ] && exit		# previous iteration did not finish

ps -ef|grep dwh_look_for_lists.ksh|grep -v grep|wc  -l|read COUNT
[ $COUNT -gt 0 ] && exit		# previous iteration did not finish

cd /ftp/common/scripts
scp -pq ecats_dwh_filelist.txt ecatsadm@oi-orca801-hi-e:/exaccstgk4/ecats/
ssh ecatsadm@oi-orca801-hi-e /home/ecatsadm/bin/send_dwh.ksh 2>/dev/null
